
server {
    listen 80;

    # Serve frontend files
    location / {
        root /templates;
        index base.html;
    }
    
    # Serve scripts (CSS/JS) 
    location /scripts/ { 
        alias /scripts/; 
        }

    # Proxy API requests to Flask backend
    location /api/ {
        proxy_pass http://backend:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
